// flow-typed signature: 1d0c9c219fbfc2aab5304f9721d321ef
// flow-typed version: <<STUB>>/eslint-config-keystone_v^3.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-keystone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-keystone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-keystone/index' {
  declare module.exports: $Exports<'eslint-config-keystone'>;
}
declare module 'eslint-config-keystone/index.js' {
  declare module.exports: $Exports<'eslint-config-keystone'>;
}
