// flow-typed signature: fb06a789f80d5e0fc31c32afd7cc964b
// flow-typed version: <<STUB>>/eslint-config-keystone-react_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-keystone-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-keystone-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-keystone-react/index' {
  declare module.exports: $Exports<'eslint-config-keystone-react'>;
}
declare module 'eslint-config-keystone-react/index.js' {
  declare module.exports: $Exports<'eslint-config-keystone-react'>;
}
