// flow-typed signature: fe245c3a11f4b1b2e2647d7b39b0d646
// flow-typed version: <<STUB>>/mockdate_v^2.0.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mockdate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mockdate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mockdate/Gruntfile' {
  declare module.exports: any;
}

declare module 'mockdate/src/mockdate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mockdate/Gruntfile.js' {
  declare module.exports: $Exports<'mockdate/Gruntfile'>;
}
declare module 'mockdate/src/mockdate.js' {
  declare module.exports: $Exports<'mockdate/src/mockdate'>;
}
