// flow-typed signature: 8fa1ff9db9f800dc014fa9ca61e23102
// flow-typed version: <<STUB>>/react-native-smart-splash-screen_v^2.3.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-smart-splash-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-smart-splash-screen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-smart-splash-screen/SplashScreen' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-smart-splash-screen/SplashScreen.js' {
  declare module.exports: $Exports<'react-native-smart-splash-screen/SplashScreen'>;
}
