// flow-typed signature: 1e789c4ec12cc6d816ee40b2cc9194b9
// flow-typed version: <<STUB>>/react-native-code-push_v^1.17.0-beta/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-code-push'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-code-push' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-code-push/AlertAdapter' {
  declare module.exports: any;
}

declare module 'react-native-code-push/CodePush' {
  declare module.exports: any;
}

declare module 'react-native-code-push/gulpfile' {
  declare module.exports: any;
}

declare module 'react-native-code-push/logging' {
  declare module.exports: any;
}

declare module 'react-native-code-push/package-mixins' {
  declare module.exports: any;
}

declare module 'react-native-code-push/request-fetch-adapter' {
  declare module.exports: any;
}

declare module 'react-native-code-push/RestartManager' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/generateBundledResourcesHash' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/getFilesInFolder' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/android/postlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/ios/postlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/run' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/recordFilesBeforeBundleCommand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-code-push/AlertAdapter.js' {
  declare module.exports: $Exports<'react-native-code-push/AlertAdapter'>;
}
declare module 'react-native-code-push/CodePush.js' {
  declare module.exports: $Exports<'react-native-code-push/CodePush'>;
}
declare module 'react-native-code-push/gulpfile.js' {
  declare module.exports: $Exports<'react-native-code-push/gulpfile'>;
}
declare module 'react-native-code-push/logging.js' {
  declare module.exports: $Exports<'react-native-code-push/logging'>;
}
declare module 'react-native-code-push/package-mixins.js' {
  declare module.exports: $Exports<'react-native-code-push/package-mixins'>;
}
declare module 'react-native-code-push/request-fetch-adapter.js' {
  declare module.exports: $Exports<'react-native-code-push/request-fetch-adapter'>;
}
declare module 'react-native-code-push/RestartManager.js' {
  declare module.exports: $Exports<'react-native-code-push/RestartManager'>;
}
declare module 'react-native-code-push/scripts/generateBundledResourcesHash.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/generateBundledResourcesHash'>;
}
declare module 'react-native-code-push/scripts/getFilesInFolder.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/getFilesInFolder'>;
}
declare module 'react-native-code-push/scripts/postlink/android/postlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/android/postlink'>;
}
declare module 'react-native-code-push/scripts/postlink/ios/postlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/ios/postlink'>;
}
declare module 'react-native-code-push/scripts/postlink/run.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/run'>;
}
declare module 'react-native-code-push/scripts/recordFilesBeforeBundleCommand.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/recordFilesBeforeBundleCommand'>;
}
