// flow-typed signature: ea1f8672584406cf7b37a509a6d73be4
// flow-typed version: <<STUB>>/react-native-maps_vairbnb/react-native-maps/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-maps/components/AnimatedRegion' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/decorateMapComponent' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapCallout' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapCircle' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapPolygon' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapPolyline' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapUrlTile' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/MapView' {
  declare module.exports: any;
}

declare module 'react-native-maps/components/ProviderConstants' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/App' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/AnimatedMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/AnimatedPriceMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/AnimatedViews' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CachedMap' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/Callouts' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CustomCallout' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CustomMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CustomOverlay' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CustomOverlayXMarksTheSpot' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/CustomTiles' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/DefaultMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/DisplayLatLng' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/DraggableMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/EventListener' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/FitToCoordinates' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/FitToSuppliedMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/LegalLabel' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/LiteMapView' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/LoadingMap' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/MapStyle' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/MarkerTypes' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/Overlays' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/PanController' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/PolygonCreator' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/PolylineCreator' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/PriceMarker' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/SetNativePropsOverlays' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/StaticMap' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/TakeSnapshot' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/ViewsAsMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/examples/ZIndexMarkers' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-maps/example/scripts/watch-and-copy-src' {
  declare module.exports: any;
}

declare module 'react-native-maps/scripts/update-version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-maps/components/AnimatedRegion.js' {
  declare module.exports: $Exports<'react-native-maps/components/AnimatedRegion'>;
}
declare module 'react-native-maps/components/decorateMapComponent.js' {
  declare module.exports: $Exports<'react-native-maps/components/decorateMapComponent'>;
}
declare module 'react-native-maps/components/MapCallout.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapCallout'>;
}
declare module 'react-native-maps/components/MapCircle.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapCircle'>;
}
declare module 'react-native-maps/components/MapMarker.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapMarker'>;
}
declare module 'react-native-maps/components/MapPolygon.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapPolygon'>;
}
declare module 'react-native-maps/components/MapPolyline.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapPolyline'>;
}
declare module 'react-native-maps/components/MapUrlTile.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapUrlTile'>;
}
declare module 'react-native-maps/components/MapView.js' {
  declare module.exports: $Exports<'react-native-maps/components/MapView'>;
}
declare module 'react-native-maps/components/ProviderConstants.js' {
  declare module.exports: $Exports<'react-native-maps/components/ProviderConstants'>;
}
declare module 'react-native-maps/example/App.js' {
  declare module.exports: $Exports<'react-native-maps/example/App'>;
}
declare module 'react-native-maps/example/examples/AnimatedMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/AnimatedMarkers'>;
}
declare module 'react-native-maps/example/examples/AnimatedPriceMarker.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/AnimatedPriceMarker'>;
}
declare module 'react-native-maps/example/examples/AnimatedViews.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/AnimatedViews'>;
}
declare module 'react-native-maps/example/examples/CachedMap.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CachedMap'>;
}
declare module 'react-native-maps/example/examples/Callouts.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/Callouts'>;
}
declare module 'react-native-maps/example/examples/CustomCallout.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CustomCallout'>;
}
declare module 'react-native-maps/example/examples/CustomMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CustomMarkers'>;
}
declare module 'react-native-maps/example/examples/CustomOverlay.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CustomOverlay'>;
}
declare module 'react-native-maps/example/examples/CustomOverlayXMarksTheSpot.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CustomOverlayXMarksTheSpot'>;
}
declare module 'react-native-maps/example/examples/CustomTiles.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/CustomTiles'>;
}
declare module 'react-native-maps/example/examples/DefaultMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/DefaultMarkers'>;
}
declare module 'react-native-maps/example/examples/DisplayLatLng.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/DisplayLatLng'>;
}
declare module 'react-native-maps/example/examples/DraggableMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/DraggableMarkers'>;
}
declare module 'react-native-maps/example/examples/EventListener.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/EventListener'>;
}
declare module 'react-native-maps/example/examples/FitToCoordinates.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/FitToCoordinates'>;
}
declare module 'react-native-maps/example/examples/FitToSuppliedMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/FitToSuppliedMarkers'>;
}
declare module 'react-native-maps/example/examples/LegalLabel.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/LegalLabel'>;
}
declare module 'react-native-maps/example/examples/LiteMapView.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/LiteMapView'>;
}
declare module 'react-native-maps/example/examples/LoadingMap.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/LoadingMap'>;
}
declare module 'react-native-maps/example/examples/MapStyle.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/MapStyle'>;
}
declare module 'react-native-maps/example/examples/MarkerTypes.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/MarkerTypes'>;
}
declare module 'react-native-maps/example/examples/Overlays.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/Overlays'>;
}
declare module 'react-native-maps/example/examples/PanController.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/PanController'>;
}
declare module 'react-native-maps/example/examples/PolygonCreator.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/PolygonCreator'>;
}
declare module 'react-native-maps/example/examples/PolylineCreator.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/PolylineCreator'>;
}
declare module 'react-native-maps/example/examples/PriceMarker.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/PriceMarker'>;
}
declare module 'react-native-maps/example/examples/SetNativePropsOverlays.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/SetNativePropsOverlays'>;
}
declare module 'react-native-maps/example/examples/StaticMap.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/StaticMap'>;
}
declare module 'react-native-maps/example/examples/TakeSnapshot.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/TakeSnapshot'>;
}
declare module 'react-native-maps/example/examples/ViewsAsMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/ViewsAsMarkers'>;
}
declare module 'react-native-maps/example/examples/ZIndexMarkers.js' {
  declare module.exports: $Exports<'react-native-maps/example/examples/ZIndexMarkers'>;
}
declare module 'react-native-maps/example/index.android.js' {
  declare module.exports: $Exports<'react-native-maps/example/index.android'>;
}
declare module 'react-native-maps/example/index.ios.js' {
  declare module.exports: $Exports<'react-native-maps/example/index.ios'>;
}
declare module 'react-native-maps/example/scripts/watch-and-copy-src.js' {
  declare module.exports: $Exports<'react-native-maps/example/scripts/watch-and-copy-src'>;
}
declare module 'react-native-maps/index' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/index.js' {
  declare module.exports: $Exports<'react-native-maps'>;
}
declare module 'react-native-maps/scripts/update-version.js' {
  declare module.exports: $Exports<'react-native-maps/scripts/update-version'>;
}
