// flow-typed signature: 10c3a1ce4d744fff5fdcc743149d2954
// flow-typed version: <<STUB>>/react-native-blur_v^2.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-blur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-blur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-blur/src/BlurView.android' {
  declare module.exports: any;
}

declare module 'react-native-blur/src/BlurView.ios' {
  declare module.exports: any;
}

declare module 'react-native-blur/src/VibrancyView.android' {
  declare module.exports: any;
}

declare module 'react-native-blur/src/VibrancyView.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-blur/index' {
  declare module.exports: $Exports<'react-native-blur'>;
}
declare module 'react-native-blur/index.js' {
  declare module.exports: $Exports<'react-native-blur'>;
}
declare module 'react-native-blur/src/BlurView.android.js' {
  declare module.exports: $Exports<'react-native-blur/src/BlurView.android'>;
}
declare module 'react-native-blur/src/BlurView.ios.js' {
  declare module.exports: $Exports<'react-native-blur/src/BlurView.ios'>;
}
declare module 'react-native-blur/src/VibrancyView.android.js' {
  declare module.exports: $Exports<'react-native-blur/src/VibrancyView.android'>;
}
declare module 'react-native-blur/src/VibrancyView.ios.js' {
  declare module.exports: $Exports<'react-native-blur/src/VibrancyView.ios'>;
}
