# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactConf2017' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactConf2017
  pod 'RNMobileCenter', '~> 0.3.0'
  pod 'MobileCenter', '~> 0.5.0'

end
